language: node_js
node_js:
  - "8"
  
services: mongodb  

cache:  
  directories:
    - "node_modules"
install:
  - npm install --force
script:


deploy:
  - provider: script
    skip_cleanup: true
    script: chmod +x ./deploy.sh && ./deploy.sh
    on:
      branch: master